# main.py
# Master controller - connects all NIDS modules together

import sys
import os
import datetime
import json
import time

# Import our modules
from sniffer import start_sniffing, get_default_interface, get_packet_summary
from rules import RuleEngine
from alerts import process_alert, print_alert_summary, load_alerts_from_log
from dashboard import print_banner, print_live_stats, show_startup_screen

# Global state
packet_count = 0
alert_count = 0
start_time = None
rule_engine = None
all_alerts = []

def on_packet_received(packet_info, raw_packet):
    """
    Called for every captured packet
    Runs all detection rules and handles any alerts
    """
    global packet_count, alert_count, all_alerts

    packet_count += 1

    # Run all detection rules on this packet
    triggered = rule_engine.analyze_packet(packet_info)

    # Handle any triggered alerts
    for alert in triggered:
        alert_count += 1
        process_alert(alert)
        all_alerts.append(alert)

    # Update dashboard every 50 packets
    if packet_count % 50 == 0:
        print_live_stats(
            packet_count,
            alert_count,
            start_time,
            all_alerts
        )

def generate_html_report(alerts, packet_summary):
    """Generate a professional HTML report of the NIDS session"""

    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    total = len(alerts)
    critical = sum(1 for a in alerts if a["severity"] == "CRITICAL")
    high = sum(1 for a in alerts if a["severity"] == "HIGH")
    medium = sum(1 for a in alerts if a["severity"] == "MEDIUM")

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>NIDS Report</title>
    <style>
        * {{ margin:0; padding:0; box-sizing:border-box; }}
        body {{ font-family: Arial, sans-serif; background:#0a0a0a; color:#e0e0e0; padding:20px; }}
        .header {{ background:linear-gradient(135deg,#1a1a2e,#0f3460); padding:40px; border-radius:12px; margin-bottom:30px; border-left:5px solid #e94560; }}
        .header h1 {{ color:#e94560; font-size:28px; margin-bottom:8px; }}
        .header p {{ color:#a0a0b0; font-size:13px; }}
        .grid {{ display:grid; grid-template-columns:repeat(4,1fr); gap:15px; margin-bottom:30px; }}
        .card {{ background:#1a1a2e; border-radius:10px; padding:20px; text-align:center; border-top:3px solid #e94560; }}
        .card .num {{ font-size:40px; font-weight:bold; color:#e94560; }}
        .card .lbl {{ font-size:12px; color:#a0a0b0; margin-top:5px; }}
        .section-title {{ color:#e94560; font-size:18px; margin:25px 0 15px; border-bottom:1px solid #333; padding-bottom:8px; }}
        .alert-card {{ background:#1a1a2e; border-radius:8px; padding:15px; margin-bottom:12px; }}
        .CRITICAL {{ border-left:4px solid #ff0000; }}
        .HIGH {{ border-left:4px solid #ff6600; }}
        .MEDIUM {{ border-left:4px solid #ffa500; }}
        .LOW {{ border-left:4px solid #008000; }}
        .badge {{ display:inline-block; padding:3px 10px; border-radius:12px; font-size:11px; font-weight:bold; color:#fff; }}
        .badge.CRITICAL {{ background:#ff0000; }}
        .badge.HIGH {{ background:#ff6600; }}
        .badge.MEDIUM {{ background:#ffa500; }}
        table {{ width:100%; border-collapse:collapse; font-size:13px; margin-top:10px; }}
        th {{ background:#0f3460; color:#00d4ff; padding:10px; text-align:left; }}
        td {{ padding:10px; border-bottom:1px solid #2a2a4a; }}
        .footer {{ text-align:center; color:#555; font-size:12px; margin-top:40px; padding-top:20px; border-top:1px solid #222; }}
        .clean {{ color:#00ff88; padding:15px; font-size:14px; }}
    </style>
</head>
<body>
<div class="header">
    <h1>🛡️ Network Intrusion Detection System Report</h1>
    <p>Session Date: {now}</p>
    <p>Generated by: NIDS v1.0 — Academic Cybersecurity Project</p>
    <p>⚠️ For authorized use only</p>
</div>

<div class="grid">
    <div class="card"><div class="num">{packet_summary.get('total',0)}</div><div class="lbl">Packets Analyzed</div></div>
    <div class="card"><div class="num">{total}</div><div class="lbl">Alerts Generated</div></div>
    <div class="card"><div class="num">{critical}</div><div class="lbl">Critical Alerts</div></div>
    <div class="card"><div class="num">{high}</div><div class="lbl">High Alerts</div></div>
</div>

<div class="section-title">📦 Packet Summary</div>
<table>
    <tr><th>Protocol</th><th>Count</th></tr>
    <tr><td>TCP</td><td>{packet_summary.get('TCP',0)}</td></tr>
    <tr><td>UDP</td><td>{packet_summary.get('UDP',0)}</td></tr>
    <tr><td>ICMP</td><td>{packet_summary.get('ICMP',0)}</td></tr>
    <tr><td>ARP</td><td>{packet_summary.get('ARP',0)}</td></tr>
    <tr><td>Unique IPs Seen</td><td>{packet_summary.get('unique_ips',0)}</td></tr>
</table>

<div class="section-title">🚨 Detected Alerts</div>
"""

    if alerts:
        for alert in alerts:
            sev = alert["severity"]
            html += f"""
<div class="alert-card {sev}">
    <span class="badge {sev}">{sev}</span>
    <strong style="color:#00d4ff; margin-left:10px">{alert['attack_type']}</strong>
    <span style="color:#a0a0b0; font-size:12px; float:right">{alert['timestamp']}</span>
    <br><br>
    <strong>Source:</strong> {alert['src_ip']} &nbsp;→&nbsp; <strong>Target:</strong> {alert['dst_ip']}<br>
    <p style="color:#a0a0b0; margin-top:8px; font-size:13px">{alert['details']}</p>
</div>"""
    else:
        html += '<p class="clean">✔ No intrusions detected during this session</p>'

    html += f"""
<div class="footer">
    <p>NIDS — Academic Cybersecurity Project | Report: {now}</p>
    <p>⚠️ For authorized and educational use only</p>
</div>
</body></html>"""

    # Save report
    report_path = os.path.join(
        os.path.dirname(__file__), "..", "reports", "nids_report.html"
    )
    os.makedirs(os.path.dirname(report_path), exist_ok=True)
    with open(report_path, "w") as f:
        f.write(html)

    print(f"\n[+] Report saved: {report_path}")
    return report_path

def run_nids(packet_limit=500):
    """Main function that starts the NIDS"""
    global rule_engine, start_time, packet_count, alert_count, all_alerts

    # Initialize
    rule_engine = RuleEngine()
    start_time = datetime.datetime.now()
    packet_count = 0
    alert_count = 0
    all_alerts = []

    # Get interface
    interface = get_default_interface()

    # Show startup screen
    show_startup_screen(interface)

    print(f"[*] Monitoring started on {interface}")
    print(f"[*] Capturing {packet_limit} packets\n")

    try:
        # Start sniffing with our callback
        packets = start_sniffing(
            interface=interface,
            packet_limit=packet_limit,
            callback=on_packet_received
        )

        # Generate summary and report
        summary = get_packet_summary(packets) if packets else {"total": packet_count}
        summary["total"] = packet_count

        # Print final summary
        print_alert_summary(all_alerts)

        # Generate HTML report
        report_path = generate_html_report(all_alerts, summary)

        # Save alerts to JSON
        json_path = os.path.join(
            os.path.dirname(__file__), "..", "logs", "session.json"
        )
        with open(json_path, "w") as f:
            json.dump({
                "session_date": start_time.strftime("%Y-%m-%d %H:%M:%S"),
                "packets_analyzed": packet_count,
                "alerts": all_alerts
            }, f, indent=2)

        print(f"[+] Session log: {json_path}")
        print(f"\n\033[92m[✔] NIDS session complete!\033[0m")
        print(f"[✔] Open report: firefox {report_path}")

    except KeyboardInterrupt:
        print("\n[!] NIDS stopped by user")

if __name__ == "__main__":
    run_nids(packet_limit=500)
